### ISSUE TITLE
java.lang.NoClassDefFoundError: io/vertx/core/file/FileSystemException

### ISSUE THREAD

**Issue by yinlingshishangS** [perkinls/flink-local-train#3]
您好，我在使用您代码的过程中，异步io导致一些问题，频繁报错，所以想咨询一下您。
`Exception in thread "Thread-13" java.lang.NoClassDefFoundError: io/vertx/core/file/FileSystemException
        at io.vertx.core.file.impl.FileSystemImpl.deleteInternal(FileSystemImpl.java:615)
        at io.vertx.core.file.impl.FileSystemImpl.deleteRecursive(FileSystemImpl.java:223)
        at io.vertx.core.impl.FileResolver.deleteCacheDir(FileResolver.java:328)
        at io.vertx.core.impl.FileResolver.lambda$setupCacheDir$1(FileResolver.java:317)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.vertx.core.file.FileSystemException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:129)`

**Comment by perkinls** [comment]
首先需要确定下你的maven包是否下载ok
